[package]
name = "squish"
version = "0.1.0"
authors = ["Josh Matthews <josh@joshmatthews.net>"]
build = "build.rs"
license = "MIT"

[build-dependencies]
gcc = "0.3"

[dependencies]
squish_sys = { path = "squish_sys" }
libc = "0.2"
